// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNIuvElv7is7j6dT3lpZMNlByCIUe5cnA',
    appId: '1:411157370253:web:3bc28da025234deb5f19c4',
    messagingSenderId: '411157370253',
    projectId: 'ml-based-personal-finance',
    authDomain: 'ml-based-personal-finance.firebaseapp.com',
    storageBucket: 'ml-based-personal-finance.firebasestorage.app',
    measurementId: 'G-LFXLEXXV75',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV0CfzdHAlDwzT-Uk0VgW1jSTLqzhTg9k',
    appId: '1:411157370253:android:c6c7c371d670fc905f19c4',
    messagingSenderId: '411157370253',
    projectId: 'ml-based-personal-finance',
    storageBucket: 'ml-based-personal-finance.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrr7uxkINHGxATVe4kuUSPHZOt4VuQK-M',
    appId: '1:411157370253:ios:14e802f9fdcda2b35f19c4',
    messagingSenderId: '411157370253',
    projectId: 'ml-based-personal-finance',
    storageBucket: 'ml-based-personal-finance.firebasestorage.app',
    iosBundleId: 'com.example.mlBasedPersonalFinanceOptimizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrr7uxkINHGxATVe4kuUSPHZOt4VuQK-M',
    appId: '1:411157370253:ios:14e802f9fdcda2b35f19c4',
    messagingSenderId: '411157370253',
    projectId: 'ml-based-personal-finance',
    storageBucket: 'ml-based-personal-finance.firebasestorage.app',
    iosBundleId: 'com.example.mlBasedPersonalFinanceOptimizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNIuvElv7is7j6dT3lpZMNlByCIUe5cnA',
    appId: '1:411157370253:web:27519087307e09695f19c4',
    messagingSenderId: '411157370253',
    projectId: 'ml-based-personal-finance',
    authDomain: 'ml-based-personal-finance.firebaseapp.com',
    storageBucket: 'ml-based-personal-finance.firebasestorage.app',
    measurementId: 'G-HP0SFT0LQZ',
  );
}
